---
- name: Install required packages
  ansible.builtin.apt:
    state: present
    name:
      - update-motd
      - figlet
      - lolcat
      - fail2ban
- name: Add the drivetmep module
  community.general.modprobe:
    name: drivetemp
    state: present
- name: Ensure PrintMotd is enabled
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PrintMotd no"
    search_string: "PrintMotd"
    state: present
...