---
- name: Install required packages
  ansible.builtin.apt:
    state: present
    name:
      - update-motd
      - figlet
      - lolcat
      - fail2ban
      - lm-sensors

- name: Add the drivetmep module
  community.general.modprobe:
    name: drivetemp
    state: present

- name: Run sensors-detect
  ansible.builtin.command: sensors-detect --auto

- name: Initialize lxd
  ansible.builtin.command: lxd init --auto

- name: Enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: Ensure PrintMotd is enabled
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PrintMotd yes"
    search_string: "PrintMotd"
    state: present

- name: Remove existing motd
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d
    - /etc/motd
    - /etc/motd.dynamic

- name: Check if MOTD news service
  ansible.builtin.stat:
    path: "/etc/default/motd-news"
  register: motd_news

- name: Disable MOTD news service
  community.general.ini_file:
    path: "/etc/default/motd-news"
    section: null
    option: "ENABLED"
    value: "0"
    no_extra_spaces: true
    mode: "0644"
    state: present
  when: motd_news.stat.exists

- name: Disable MOTD news timer
  ansible.builtin.systemd:
    name: motd-news.timer
    state: stopped
    enabled: no

- name: Create dynamic motd directory
  ansible.builtin.file:
    path: /etc/update-motd.d
    state: directory
    mode: 0775

- name: Clone forked MOTD scripts
  git:
    repo: https://github.com/Shadowsteelx/motd.git
    dest: /srv/git/motd

- name: Copy MOTD files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/update-motd.d/
    force: true
    mode: 0775
  with_fileglob: "/srv/git/motd/*-*"

- name: Check if '/etc/ssh/sshd_config' exists
  ansible.builtin.stat:
    path: "/etc/ssh/sshd_config"
  register: sshd_config

- name: Install 'openssh-server'
  ansible.builtin.apt:
    name: openssh-server
    state: present
  when: (not sshd_config.stat.exists)

- name: Wait for '/etc/ssh/sshd_config' to be created
  ansible.builtin.wait_for:
    path: "/etc/ssh/sshd_config"
    state: present
  when: (not sshd_config.stat.exists)

- name: Set 'PrintLastLog no' to '/etc/ssh/sshd_config'
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^PrintLastLog\s?'
    line: 'PrintLastLog no'
    state: present

- name: Update motd
  ansible.builtin.command: update-motd
...