---
- name: Set timezone
  community.general.timezone:
    name: {{ timezone }}
- name: User Account | Set sudo group to 'NOPASSWD'
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    regexp: '^%sudo\s'
    line: '%sudo   ALL=(ALL) NOPASSWD:ALL'
    state: present
  when: disable_sudo_password
...